services:
  server:
    container_name: coupon-be
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - 8080:8080
    networks:
      - backend
    
  mysql:
    image: mysql:latest
    container_name: coupon-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: zalopay
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  backend:

volumes:
  mysql:
